const faqs = [
  {
    "question": "How much information do I need to provide?",
    "answer": "The more details you provide about what happened, who was involved, and the stakes, the better we can tailor your personalized apology. Any additional information you'd like to include will help make your apology as sincere and effective as possible."
  },
  {
    "question": "Do third parties have access to what gets generated?",
    "answer": "No third parties have access to the apologies generated, other than the Language Learning Model (LLM) we use to process your inputs and craft your apology. Your privacy and confidentiality are paramount to us."
  },
  {
    "question": "How much typing do I have to do?",
    "answer": "You only need to type once when describing the situation you'd like to apologize for. After that, everything else involves simple clicks to navigate through the process and finalize your apology."
  },
  {
    "question": "Can I use an iSorry.lol generated apology commercially?",
    "answer": "As of the time of this writing, AI-generated content cannot be copyrighted in the US, which suggests that you can use the apologies generated by iSorry.lol for commercial purposes. However, it's always a good idea to consult with a legal professional regarding the latest laws and regulations."
  }
];

  
  export default function FAQ() {
    return (
      <div className="bg-white" id='faq'>
        <div className="mx-auto max-w-7xl divide-y divide-gray-900/10 px-6 py-24 sm:py-32 lg:px-8 lg:py-40">
          <h2 className="text-2xl font-bold leading-10 tracking-tight text-gray-900">Frequently asked questions</h2>
          <dl className="mt-10 space-y-8 divide-y divide-gray-900/10">
            {faqs.map((faq, index) => (
              <div key={index+1} className="pt-8 lg:grid lg:grid-cols-12 lg:gap-8">
                <dt className="text-base font-semibold leading-7 text-gray-900 lg:col-span-5">{faq.question}</dt>
                <dd className="mt-4 lg:col-span-7 lg:mt-0">
                  <p className="text-base leading-7 text-gray-600">{faq.answer}</p>
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </div>
    )
  }
  